### ISSUE TITLE
Single quotes in svg files are replaced by \i

### ISSUE THREAD

**Issue by jaap3** [filamentgroup/directory-encoder#37] opened 2017-03-20 14:11 UTC
When an svg contains (e.g.) attributes that are enclosed by single quotes the resulting encoded string contains "\i" instead of the single quote. This makes the svg file invalid.

**Comment by zachleat** [comment] 2018-12-18 22:53
I _think_ this is a duplicate of the issue fixed in https://github.com/filamentgroup/directory-encoder/pull/39

**Comment by zachleat** [comment] 2018-12-18 22:53
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2018-12-18 22:53 UTC
Labels: duplicate
