### ISSUE TITLE
svg encoding not work in ie11

### ISSUE THREAD

**Issue by shikelong** [filamentgroup/directory-encoder#40] opened 2017-12-05 02:18 UTC
In ie11, the [optimizing encoding](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) not work when the svg has style tag.

The online demo:
https://jsbin.com/rapucof/edit?html,css,output

**Comment by zachleat** [comment] 2018-12-18 22:34
## IE11:
![image](https://user-images.githubusercontent.com/39355/50187133-c4417780-02e2-11e9-9433-ace9c4b18f29.png)

## Firefox:
![image](https://user-images.githubusercontent.com/39355/50187149-d02d3980-02e2-11e9-9e64-1353664d841a.png)

**Comment by zachleat** [comment] 2018-12-18 22:56
This is likely a duplicate of #39!

**Closed by zachleat** 2018-12-18 22:56 UTC
Labels: bug
